/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#fff8f5',
        'surface-dim': '#e1d8d4',
        'surface-bright': '#fff8f5',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#fbf2ed',
        'surface-container': '#f5ece7',
        'surface-container-high': '#efe6e2',
        'surface-container-highest': '#e9e1dc',
        'on-surface': '#1e1b18',
        'on-surface-variant': '#3f484b',
        'inverse-surface': '#34302c',
        'inverse-on-surface': '#f8efea',
        outline: '#6f797c',
        'outline-variant': '#bec8cb',
        'surface-tint': '#086878',
        primary: 'var(--color-primary)',
        'on-primary': 'var(--color-on-primary)',
        'primary-container': '#2d7d8e',
        'on-primary-container': '#f3fcff',
        'inverse-primary': '#87d2e4',
        'kid-primary': 'var(--color-primary)',
        'kid-primary-container': '#4FD8E3',
        'kid-secondary': 'var(--color-secondary)',
        'kid-secondary-container': '#FFC157',
        secondary: 'var(--color-secondary)',
        'on-secondary': 'var(--color-on-primary)',
        'secondary-container': '#fea520',
        'on-secondary-container': '#694000',
        tertiary: '#7f5018',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#9c682e',
        'on-tertiary-container': '#fff9f7',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#a9edff',
        'primary-fixed-dim': '#87d2e4',
        'on-primary-fixed': '#001f26',
        'on-primary-fixed-variant': '#004e5b',
        'secondary-fixed': '#ffddb9',
        'secondary-fixed-dim': '#ffb961',
        'on-secondary-fixed': '#2b1700',
        'on-secondary-fixed-variant': '#663e00',
        'tertiary-fixed': '#ffdcbd',
        'tertiary-fixed-dim': '#faba78',
        'on-tertiary-fixed': '#2c1600',
        'on-tertiary-fixed-variant': '#683d03',
        background: 'var(--color-background)',
        'on-background': 'var(--color-foreground)',
        'surface-variant': '#e9e1dc',
      },
      fontFamily: {
        'display': ['var(--font-display)', 'sans-serif'],
        'body': ['var(--font-body)', 'sans-serif'],
        'mono': ['var(--font-mono)', 'monospace'],
      },
      maxWidth: {
        'max-content-width': '1024px',
      },
      borderRadius: {
        'sm': '0.25rem',
        DEFAULT: '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px',
      },
      spacing: {
        'unit': '8px',
        'container-padding': '24px',
        'gutter': '16px',
        'card-gap': '24px',
      },
    },
  },
  plugins: [],
}