version: '3.8'

services:
  lexi-db:
    image: postgres:15-alpine
    container_name: lexi-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lexi
    ports:
      - "5433:5432"
    volumes:
      - lexi_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  lexi-redis:
    image: redis:7-alpine
    container_name: lexi-redis
    ports:
      - "6379:6379"
    volumes:
      - lexi_redisdata:/data
    restart: unless-stopped

volumes:
  lexi_pgdata:
  lexi_redisdata:
